package projectfarhan;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class AllRec_frame extends javax.swing.JFrame {

    Connection con;

    public AllRec_frame() {
        initComponents();

        ProjectFarhan cnt = new ProjectFarhan();
        cnt.connectDB();
        con = cnt.con;

        allRecTable();
    }

    public void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    public void searchRecTable() {
        try {
            Statement statement = con.createStatement();


            /*String query = "SELECT O.orphanID, O.firstname, O.age, O.adoptionstatus, A.adopterID, A.adoptername, A.phoneno\n" +
                                        "FROM orphan O, adopter A \n" +
                                        "WHERE O.orphanID=A.orphanID AND O.orphanID= " + SearchIDTF.getText(); */
            String query = "SELECT O.orphanID, O.firstname, O.age, O.adoptionstatus, A.adopterID, A.adoptername, A.phoneno\n"
                    + "FROM orphan O LEFT JOIN adopter A \n"
                    + "ON O.orphanID=A.orphanID WHERE O.orphanID= " + SearchIDTF.getText();
            ResultSet rs = statement.executeQuery(query);

            ResultSetMetaData RSM = rs.getMetaData();
            int c;
            c = RSM.getColumnCount();

            DefaultTableModel DF = (DefaultTableModel) SearchRecTableM.getModel();
            DF.setRowCount(0);

            while (rs.next()) {
                Vector v2 = new Vector();
                for (int i = 1; i <= c; i++) {
                    v2.add(rs.getString("orphanID"));
                    v2.add(rs.getString("firstname"));
                    v2.add(rs.getString("age"));
                    v2.add(rs.getString("adoptionstatus"));
                    v2.add(rs.getString("adopterID"));
                    v2.add(rs.getString("adoptername"));
                    v2.add(rs.getString("phoneno"));
                }
                DF.addRow(v2);
                
            }
            if(DF.getRowCount()==0){
                JOptionPane.showMessageDialog(null, "Orphan ID doesn't exist", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void allRecTable() {
        try {
            Statement statement = con.createStatement();

            /*String query = "SELECT O.orphanID, O.firstname, O.age, O.adoptionstatus, A.adopterID, A.adoptername, A.phoneno\n"
                    + "FROM orphan O, adopter A \n"
                    + "WHERE O.orphanID=A.orphanID";*/

            String query = "SELECT O.orphanID, O.firstname, O.age, O.adoptionstatus, A.adopterID, A.adoptername, A.phoneno\n"
                    + "FROM orphan O LEFT JOIN adopter A ON O.orphanID=A.orphanID";
            ResultSet rs = statement.executeQuery(query);

            ResultSetMetaData RSM = rs.getMetaData();
            int c;
            c = RSM.getColumnCount();

            DefaultTableModel DF = (DefaultTableModel) AllRecTableM.getModel();
            DF.setRowCount(0);

            while (rs.next()) {
                Vector v2 = new Vector();
                for (int i = 1; i <= c; i++) {
                    v2.add(rs.getString("orphanID"));
                    v2.add(rs.getString("firstname"));
                    v2.add(rs.getString("age"));
                    v2.add(rs.getString("adoptionstatus"));
                    v2.add(rs.getString("adopterID"));
                    v2.add(rs.getString("adoptername"));
                    v2.add(rs.getString("phoneno"));
                }
                DF.addRow(v2);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSButtonHover2 = new rojerusan.RSButtonHover();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        SearchIDTF = new app.bolivia.swing.JCTextField();
        jLabel1 = new javax.swing.JLabel();
        SearchBtn = new rojerusan.RSMaterialButtonRectangle();
        jScrollPane1 = new javax.swing.JScrollPane();
        AllRecTableM = new rojerusan.RSTableMetro();
        jScrollPane2 = new javax.swing.JScrollPane();
        SearchRecTableM = new rojerusan.RSTableMetro();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("OMS - ALL RECORDS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonHover2.setBackground(new java.awt.Color(0, 51, 102));
        rSButtonHover2.setBorder(null);
        rSButtonHover2.setText("BACK");
        rSButtonHover2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rSButtonHover2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover2ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonHover2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 0, 100, 50));

        jPanel2.setBackground(new java.awt.Color(218, 239, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("All Information");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(110, 5));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 110, 5));

        SearchIDTF.setBackground(new java.awt.Color(218, 239, 255));
        SearchIDTF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        SearchIDTF.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        SearchIDTF.setPlaceholder("Enter Valid Orphan ID...");
        jPanel2.add(SearchIDTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 530, 30));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Search Orphan ID :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 170, 30));

        SearchBtn.setBackground(new java.awt.Color(0, 51, 102));
        SearchBtn.setText("SEARCH");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });
        jPanel2.add(SearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 110, 110, 45));

        AllRecTableM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Orphan ID", "Orphan Name", "Orphan Age", "Adoption Status", "Adopter ID", "Adopter Name", "Adopter Phone"
            }
        ));
        AllRecTableM.setColorBackgoundHead(new java.awt.Color(102, 153, 255));
        AllRecTableM.setColorBordeFilas(new java.awt.Color(153, 204, 255));
        AllRecTableM.setColorBordeHead(new java.awt.Color(102, 153, 255));
        AllRecTableM.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        AllRecTableM.setColorFilasForeground1(new java.awt.Color(51, 51, 51));
        AllRecTableM.setColorFilasForeground2(new java.awt.Color(51, 51, 51));
        AllRecTableM.setColorSelBackgound(new java.awt.Color(255, 255, 255));
        AllRecTableM.setColorSelForeground(new java.awt.Color(51, 51, 51));
        AllRecTableM.setFuenteFilas(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AllRecTableM.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AllRecTableM.setFuenteHead(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        AllRecTableM.setRowHeight(28);
        jScrollPane1.setViewportView(AllRecTableM);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 1100, 360));

        SearchRecTableM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Orphan ID", "Orphan Name", "Orphan Age", "Adoption Status", "Adopter ID", "Adopter Name", "Adopter Phone"
            }
        ));
        SearchRecTableM.setColorBackgoundHead(new java.awt.Color(102, 153, 255));
        SearchRecTableM.setColorBordeFilas(new java.awt.Color(153, 204, 255));
        SearchRecTableM.setColorBordeHead(new java.awt.Color(102, 153, 255));
        SearchRecTableM.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        SearchRecTableM.setColorFilasForeground1(new java.awt.Color(51, 51, 51));
        SearchRecTableM.setColorFilasForeground2(new java.awt.Color(51, 51, 51));
        SearchRecTableM.setColorSelBackgound(new java.awt.Color(255, 255, 255));
        SearchRecTableM.setColorSelForeground(new java.awt.Color(51, 51, 51));
        SearchRecTableM.setFuenteFilas(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SearchRecTableM.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SearchRecTableM.setFuenteHead(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        SearchRecTableM.setMinimumSize(new java.awt.Dimension(105, 28));
        SearchRecTableM.setRowHeight(27);
        jScrollPane2.setViewportView(SearchRecTableM);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 1100, 120));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("All Records");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonHover2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover2ActionPerformed
        // TODO add your handling code here:
        close();
        Home_Frame h = new Home_Frame();
        h.setVisible(true);
    }//GEN-LAST:event_rSButtonHover2ActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
        searchRecTable();
    }//GEN-LAST:event_SearchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllRec_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllRec_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllRec_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllRec_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllRec_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSTableMetro AllRecTableM;
    private rojerusan.RSMaterialButtonRectangle SearchBtn;
    private app.bolivia.swing.JCTextField SearchIDTF;
    private rojerusan.RSTableMetro SearchRecTableM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private rojerusan.RSButtonHover rSButtonHover2;
    // End of variables declaration//GEN-END:variables
}
